
package org.flowframe.erp.integration.adaptors.services.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-06-20T13:48:01.477-04:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "Exception", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/")
public class Exception_Exception extends java.lang.Exception {
    
    private org.flowframe.erp.integration.adaptors.services.soap.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, org.flowframe.erp.integration.adaptors.services.soap.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, org.flowframe.erp.integration.adaptors.services.soap.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public org.flowframe.erp.integration.adaptors.services.soap.Exception getFaultInfo() {
        return this.exception;
    }
}
