package org.flowframe.erp.integration.adaptors.services.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-06-20T13:48:00.891-04:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", name = "IEventDAOServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IEventDAOServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.AddResponse")
    public org.flowframe.erp.integration.adaptors.services.soap.Event add(
        @WebParam(name = "arg0", targetNamespace = "")
        org.flowframe.erp.integration.adaptors.services.soap.Event arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getEventById", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.GetEventById")
    @WebMethod
    @ResponseWrapper(localName = "getEventByIdResponse", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.GetEventByIdResponse")
    public org.flowframe.erp.integration.adaptors.services.soap.Event getEventById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "provide", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.Provide")
    @WebMethod
    @ResponseWrapper(localName = "provideResponse", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.ProvideResponse")
    public org.flowframe.erp.integration.adaptors.services.soap.Event provide(
        @WebParam(name = "arg0", targetNamespace = "")
        org.flowframe.erp.integration.adaptors.services.soap.Event arg0
    ) throws Exception_Exception;

    @RequestWrapper(localName = "delete", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.Get")
    @WebMethod
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.GetResponse")
    public org.flowframe.erp.integration.adaptors.services.soap.Event get(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @RequestWrapper(localName = "resetDB", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.ResetDB")
    @WebMethod
    @ResponseWrapper(localName = "resetDBResponse", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.ResetDBResponse")
    public void resetDB();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllInvoiceEventsCreated", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.GetAllInvoiceEventsCreated")
    @WebMethod
    @ResponseWrapper(localName = "getAllInvoiceEventsCreatedResponse", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.GetAllInvoiceEventsCreatedResponse")
    public java.util.List<org.flowframe.erp.integration.adaptors.services.soap.Event> getAllInvoiceEventsCreated();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getByCode", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.GetByCode")
    @WebMethod
    @ResponseWrapper(localName = "getByCodeResponse", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.GetByCodeResponse")
    public org.flowframe.erp.integration.adaptors.services.soap.Event getByCode(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.UpdateResponse")
    public org.flowframe.erp.integration.adaptors.services.soap.Event update(
        @WebParam(name = "arg0", targetNamespace = "")
        org.flowframe.erp.integration.adaptors.services.soap.Event arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllInvoiceEventsWithFailedPayment", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.GetAllInvoiceEventsWithFailedPayment")
    @WebMethod
    @ResponseWrapper(localName = "getAllInvoiceEventsWithFailedPaymentResponse", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.GetAllInvoiceEventsWithFailedPaymentResponse")
    public java.util.List<org.flowframe.erp.integration.adaptors.services.soap.Event> getAllInvoiceEventsWithFailedPayment();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllActiveEvents", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.GetAllActiveEvents")
    @WebMethod
    @ResponseWrapper(localName = "getAllActiveEventsResponse", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.GetAllActiveEventsResponse")
    public java.util.List<org.flowframe.erp.integration.adaptors.services.soap.Event> getAllActiveEvents();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.GetAll")
    @WebMethod
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.GetAllResponse")
    public java.util.List<org.flowframe.erp.integration.adaptors.services.soap.Event> getAll();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllInvoiceEventsWithSuccessfulPayment", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.GetAllInvoiceEventsWithSuccessfulPayment")
    @WebMethod
    @ResponseWrapper(localName = "getAllInvoiceEventsWithSuccessfulPaymentResponse", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.GetAllInvoiceEventsWithSuccessfulPaymentResponse")
    public java.util.List<org.flowframe.erp.integration.adaptors.services.soap.Event> getAllInvoiceEventsWithSuccessfulPayment();

    @RequestWrapper(localName = "delete1", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.Delete1")
    @WebMethod
    @ResponseWrapper(localName = "delete1Response", targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/", className = "org.flowframe.erp.integration.adaptors.services.soap.Delete1Response")
    public void delete1(
        @WebParam(name = "arg0", targetNamespace = "")
        org.flowframe.erp.integration.adaptors.services.soap.Event arg0
    );
}
