//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.03 at 01:46:20 PM EST 
//


package org.flowframe.kernel.common.mdm.domain.preferences;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.flowframe.kernel.common.mdm.domain.preferences package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Prefmap_QNAME = new QName("http://flowframe.org/kernel/common/mdm/domain/preferences", "prefmap");
    private final static QName _Prefnode_QNAME = new QName("http://flowframe.org/kernel/common/mdm/domain/preferences", "prefnode");
    private final static QName _Prefentry_QNAME = new QName("http://flowframe.org/kernel/common/mdm/domain/preferences", "prefentry");
    private final static QName _Prefroot_QNAME = new QName("http://flowframe.org/kernel/common/mdm/domain/preferences", "prefroot");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.flowframe.kernel.common.mdm.domain.preferences
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Preferences }
     * 
     */
    public Preferences createPreferences() {
        return new Preferences();
    }

    /**
     * Create an instance of {@link Prefroot }
     * 
     */
    public Prefroot createPrefroot() {
        return new Prefroot();
    }

    /**
     * Create an instance of {@link Prefentry }
     * 
     */
    public Prefentry createPrefentry() {
        return new Prefentry();
    }

    /**
     * Create an instance of {@link Prefmap }
     * 
     */
    public Prefmap createPrefmap() {
        return new Prefmap();
    }

    /**
     * Create an instance of {@link Prefnode }
     * 
     */
    public Prefnode createPrefnode() {
        return new Prefnode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prefmap }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://flowframe.org/kernel/common/mdm/domain/preferences", name = "prefmap")
    public JAXBElement<Prefmap> createPrefmap(Prefmap value) {
        return new JAXBElement<Prefmap>(_Prefmap_QNAME, Prefmap.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prefnode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://flowframe.org/kernel/common/mdm/domain/preferences", name = "prefnode")
    public JAXBElement<Prefnode> createPrefnode(Prefnode value) {
        return new JAXBElement<Prefnode>(_Prefnode_QNAME, Prefnode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prefentry }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://flowframe.org/kernel/common/mdm/domain/preferences", name = "prefentry")
    public JAXBElement<Prefentry> createPrefentry(Prefentry value) {
        return new JAXBElement<Prefentry>(_Prefentry_QNAME, Prefentry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prefroot }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://flowframe.org/kernel/common/mdm/domain/preferences", name = "prefroot")
    public JAXBElement<Prefroot> createPrefroot(Prefroot value) {
        return new JAXBElement<Prefroot>(_Prefroot_QNAME, Prefroot.class, null, value);
    }

}
