//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.03 at 01:46:20 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://flowframe.org/kernel/common/mdm/domain/preferences", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.flowframe.kernel.common.mdm.domain.preferences;
