//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.03 at 01:46:20 PM EST 
//

package org.flowframe.kernel.common.mdm.domain.preferences;

import java.io.Serializable;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.flowframe.kernel.common.mdm.domain.MultitenantBaseEntity;


@Entity(name = "Preferences")
@Table(name = "ffpreferences")
public class Preferences extends MultitenantBaseEntity implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7869822230680505559L;
	@ManyToOne(targetEntity = Prefroot.class, cascade = { CascadeType.ALL }, fetch = FetchType.EAGER)
	@JoinColumn(name = "PREFROOT_PREFERENCES_HJID")
	protected Prefroot prefroot;
	protected String externalxmlversion;

	/**
	 * Gets the value of the prefroot property.
	 * 
	 * @return possible object is {@link Prefroot }
	 * 
	 */
	public Prefroot getPrefroot() {
		return prefroot;
	}

	/**
	 * Sets the value of the prefroot property.
	 * 
	 * @param value
	 *            allowed object is {@link Prefroot }
	 * 
	 */
	public void setPrefroot(Prefroot value) {
		this.prefroot = value;
	}

	/**
	 * Gets the value of the externalxmlversion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Basic
	@Column(name = "EXTERNALXMLVERSION", length = 255)
	public String getEXTERNALXMLVERSION() {
		if (externalxmlversion == null) {
			return "0.0";
		} else {
			return externalxmlversion;
		}
	}

	/**
	 * Sets the value of the externalxmlversion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEXTERNALXMLVERSION(String value) {
		this.externalxmlversion = value;
	}
}
