//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.03 at 01:46:20 PM EST 
//

package org.flowframe.kernel.common.mdm.domain.preferences;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity(name = "Prefroot")
@Table(name = "ffprefroot")
@Inheritance(strategy = InheritanceType.JOINED)
public class Prefroot implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7869822230680505779L;
	protected Prefmap prefmap;
	protected Set<Prefnode> prefnode;
	protected String type;
	protected Long hjid;

	/**
	 * Gets the value of the prefmap property.
	 * 
	 * @return possible object is {@link Prefmap }
	 * 
	 */
	@ManyToOne(targetEntity = Prefmap.class, cascade = { CascadeType.ALL })
	@JoinColumn(name = "PREFMAP_PREFROOT_HJID")
	public Prefmap getPrefmap() {
		return prefmap;
	}

	/**
	 * Sets the value of the prefmap property.
	 * 
	 * @param value
	 *            allowed object is {@link Prefmap }
	 * 
	 */
	public void setPrefmap(Prefmap value) {
		this.prefmap = value;
	}

	/**
	 * Gets the value of the prefnode property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the prefnode property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPrefnode().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Prefnode }
	 * 
	 * 
	 */
	@OneToMany(targetEntity = Prefnode.class, cascade = { CascadeType.ALL }, fetch = FetchType.EAGER)
	@JoinColumn(name = "PREFNODE_PREFROOT_HJID")
	public Set<Prefnode> getPrefnode() {
		if (prefnode == null) {
			prefnode = new HashSet<Prefnode>();
		}
		return this.prefnode;
	}

	/**
     * 
     * 
     */
	public void setPrefnode(Set<Prefnode> prefnode) {
		this.prefnode = prefnode;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Basic
	@Column(name = "TYPE_")
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value) {
		this.type = value;
	}

	/**
	 * Gets the value of the hjid property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	@Id
	@Column(name = "HJID")
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Long getHjid() {
		return hjid;
	}

	/**
	 * Sets the value of the hjid property.
	 * 
	 * @param value
	 *            allowed object is {@link Long }
	 * 
	 */
	public void setHjid(Long value) {
		this.hjid = value;
	}
}
