//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.03 at 01:46:20 PM EST 
//


package org.flowframe.kernel.common.mdm.domain.preferences;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for prefmap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="prefmap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://flowframe.org/kernel/common/mdm/domain/preferences}prefentry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "prefmap", propOrder = {
    "prefentry"
})
@Entity(name = "Prefmap")
@Table(name = "ffprefmap")
@Inheritance(strategy = InheritanceType.JOINED)
public class Prefmap
    implements Equals, HashCode
{
    @OneToMany(targetEntity = Prefentry.class, cascade = {
        CascadeType.ALL
    },fetch=FetchType.EAGER)
    @JoinColumn(name = "PREFENTRY_PREFMAP_HJID")
    protected List<Prefentry> prefentry;
    
    @XmlAttribute(name = "Hjid")
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)    
    protected Long hjid;

    /**
     * Gets the value of the prefentry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prefentry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrefentry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Prefentry }
     * 
     * 
     */
    public List<Prefentry> getPrefentry() {
        if (prefentry == null) {
            prefentry = new ArrayList<Prefentry>();
        }
        return this.prefentry;
    }

    /**
     * 
     * 
     */
    public void setPrefentry(List<Prefentry> prefentry) {
        this.prefentry = prefentry;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Prefmap)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Prefmap that = ((Prefmap) object);
        {
            List<Prefentry> lhsPrefentry;
            lhsPrefentry = this.getPrefentry();
            List<Prefentry> rhsPrefentry;
            rhsPrefentry = that.getPrefentry();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "prefentry", lhsPrefentry), LocatorUtils.property(thatLocator, "prefentry", rhsPrefentry), lhsPrefentry, rhsPrefentry)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<Prefentry> thePrefentry;
            thePrefentry = this.getPrefentry();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "prefentry", thePrefentry), currentHashCode, thePrefentry);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
