//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.09 at 12:50:36 AM EST 
//


package org.flowframe.kernel.common.mdm.domain;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.Transient;

import org.flowframe.kernel.common.mdm.domain.organization.Organization;


@MappedSuperclass
public abstract class MultitenantBaseEntity
    extends BaseEntity
{
    @ManyToOne(targetEntity = Organization.class, fetch = FetchType.EAGER, cascade={CascadeType.REFRESH})
    @JoinColumn
	protected Organization tenant;
    
    @Transient
    protected long tenantId;

    
    protected boolean tenantWide = false;
    
    /**
     * Gets the value of the tenantId property.
     * 
     */
    public long getTenantId() {
    	if (this.tenant != null)
    		return this.tenant.getId();
    	else
    		return 0;
    }

    
    public Organization getTenant() {
    	return this.tenant;
    }
    
    public void setTenant(Organization tenant) {
    	this.tenant = tenant;
    }   
    
    @Transient
    public String getTenantName() {
    	return this.tenant != null?this.tenant.getName():null;
    }  

    public boolean isTenantWide() {
		return tenantWide;
	}

	public void setTenantWide(boolean tenantWide) {
		this.tenantWide = tenantWide;
	}
}
