//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 12:54:59 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kettle.pentaho.org/schema/kettle/trans", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.pentaho.kettle.schema.kettle.trans;
