//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.05 at 10:11:16 AM EST 
//


package com.conx.bi.kernel.core.domain.etl.trans;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;

@Entity
@Table(name = "bietlstep_gui")
@Inheritance(strategy = InheritanceType.JOINED)
public class Stepgui
{

    protected int xloc;
    protected int yloc;
    protected String draw;
    protected Long hjid;

    /**
     * Gets the value of the xloc property.
     * 
     */
    @Basic
    @Column(name = "XLOC", precision = 5, scale = 0)
    public int getXloc() {
        return xloc;
    }

    /**
     * Sets the value of the xloc property.
     * 
     */
    public void setXloc(int value) {
        this.xloc = value;
    }

    /**
     * Gets the value of the yloc property.
     * 
     */
    @Basic
    @Column(name = "YLOC", precision = 5, scale = 0)
    public int getYloc() {
        return yloc;
    }

    /**
     * Sets the value of the yloc property.
     * 
     */
    public void setYloc(int value) {
        this.yloc = value;
    }

    /**
     * Gets the value of the draw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "DRAW", length = 255)
    public String getDraw() {
        return draw;
    }

    /**
     * Sets the value of the draw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDraw(String value) {
        this.draw = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }
}
