//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.05 at 09:00:43 PM EST 
//


package com.conx.bi.kernel.core.domain.etl.trans;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;


@Entity
@Table(name = "bietlstep_fields")
@Inheritance(strategy = InheritanceType.JOINED)
public class Stepfields
    implements Serializable
{

    protected String selectUnspecified;
    protected Set<Stepfieldsmeta> meta;
    protected Set<Stepfieldsfield> fld;
    protected Long hjid;

    /**
     * Gets the value of the selectUnspecified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "SELECTUNSPECIFIED", length = 255)
    public String getSelectUnspecified() {
        return selectUnspecified;
    }

    /**
     * Sets the value of the selectUnspecified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectUnspecified(String value) {
        this.selectUnspecified = value;
    }

    /**
     * Gets the value of the meta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Stepfieldsmeta }
     * 
     * 
     */
    @OneToMany(targetEntity = Stepfieldsmeta.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "META_STEPFIELDS_HJID")
    public Set<Stepfieldsmeta> getMeta() {
        if (meta == null) {
            meta = new HashSet<Stepfieldsmeta>();
        }
        return this.meta;
    }

    /**
     * 
     * 
     */
    public void setMeta(Set<Stepfieldsmeta> meta) {
        this.meta = meta;
    }

    /**
     * Gets the value of the fld property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fld property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFld().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Stepfieldsfield }
     * 
     * 
     */
    @OneToMany(targetEntity = Stepfieldsfield.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "FLD_STEPFIELDS_HJID")
    public Set<Stepfieldsfield> getFld() {
        if (fld == null) {
            fld = new HashSet<Stepfieldsfield>();
        }
        return this.fld;
    }

    /**
     * 
     * 
     */
    public void setFld(Set<Stepfieldsfield> fld) {
        this.fld = fld;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }
}
