//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.07 at 10:18:48 AM EST 
//

package com.conx.bi.kernel.core.domain.etl.trans;

import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.flowframe.kernel.common.mdm.domain.MultitenantBaseEntity;
import org.flowframe.kernel.common.mdm.domain.documentlibrary.FileEntry;
import org.flowframe.kernel.common.mdm.domain.preferences.EntityPreferenceItem;
import org.flowframe.kernel.common.mdm.domain.preferences.Preferences;

@Entity
@Table(name = "bietlstepmeta")
public class StepMeta extends MultitenantBaseEntity {

	protected boolean istemplate;
	
	protected String typeName;
	
	@OneToMany(mappedBy = "parentStepMeta", cascade = CascadeType.ALL)
    private Set<InputFieldMeta> fields = new java.util.HashSet<InputFieldMeta>();
	
	@ManyToOne(targetEntity = StepMeta.class, cascade = { CascadeType.REFRESH })
	@JoinColumn(name = "TEMPLATE_STEPMETA_ID")
	protected StepMeta templateStepMeta;
	
	protected TRANSFORMTYPE transformType;	
	
    @ManyToOne(targetEntity = FileEntry.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "SAMPLE_FILEENTRY_STEP_HJID")    
    protected FileEntry sampleFileEntry;
	
	public Set<InputFieldMeta> getFields() {
		return fields;
	}

	public void setFields(Set<InputFieldMeta> fields) {
		this.fields = fields;
	}

	/**
	 * Gets the value of the istemplate property.
	 * 
	 */
	@Basic
	@Column(name = "ISTEMPLATE")
	public boolean isIstemplate() {
		return istemplate;
	}

	/**
	 * Sets the value of the istemplate property.
	 * 
	 */
	public void setIstemplate(boolean value) {
		this.istemplate = value;
	}

	public StepMeta getTemplateStepMeta() {
		return templateStepMeta;
	}

	public void setTemplateStepMeta(StepMeta templateStepMeta) {
		this.templateStepMeta = templateStepMeta;
	}
	
	public TRANSFORMTYPE getTransformType() {
		return transformType;
	}

	public void setTransformType(TRANSFORMTYPE transformType) {
		this.transformType = transformType;
	}

	public FileEntry getSampleFileEntry() {
		return sampleFileEntry;
	}

	public void setSampleFileEntry(FileEntry sampleFileEntry) {
		this.sampleFileEntry = sampleFileEntry;
	}
}
