//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.05 at 10:11:16 AM EST 
//


package com.conx.bi.kernel.core.domain.etl.trans;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.flowframe.kernel.common.mdm.domain.MultitenantBaseEntity;
import org.flowframe.kernel.common.mdm.domain.documentlibrary.FileEntry;


@Entity
@Table(name = "bietlstep")
public class Step
    extends MultitenantBaseEntity
{
    @ManyToOne(targetEntity = FileEntry.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "SAMPLE_FILEENTRY_STEP_HJID")    
    protected FileEntry sampleFileEntry;    
    
    
    @ManyToOne(targetEntity = StepMeta.class, cascade = {
        CascadeType.REFRESH
    })
    @JoinColumn(name = "STEPMETA_HJID")    
    protected StepMeta stepMeta;      
    
    
    @ManyToOne(targetEntity = Stepfields.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "FIELDS_STEP_HJID")    
    protected Stepfields fields = new Stepfields();
    
    protected String clusterSchema;
    
    @ManyToOne(targetEntity = Stepremotesteps.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "REMOTESTEPS_STEP_HJID")    
    protected Stepremotesteps remotesteps;
    
    
    @ManyToOne(targetEntity = Stepgui.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "GUI_STEP_HJID")   
    protected Stepgui gui;

	protected TRANSFORMTYPE transformType;



    public FileEntry getSampleFileEntry() {
		return sampleFileEntry;
	}

	public void setSampleFileEntry(FileEntry sampleFileEntry) {
		this.sampleFileEntry = sampleFileEntry;
	}



    /**
     * Gets the value of the fields property.
     * 
     * @return
     *     possible object is
     *     {@link Stepfields }
     *     
     */
    public Stepfields getFields() {
        return fields;
    }

    /**
     * Sets the value of the fields property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stepfields }
     *     
     */
    public void setFields(Stepfields value) {
        this.fields = value;
    }

    /**
     * Gets the value of the clusterSchema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "CLUSTERSCHEMA", length = 255)
    public String getClusterSchema() {
        return clusterSchema;
    }

    /**
     * Sets the value of the clusterSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClusterSchema(String value) {
        this.clusterSchema = value;
    }

    /**
     * Gets the value of the remotesteps property.
     * 
     * @return
     *     possible object is
     *     {@link Stepremotesteps }
     *     
     */
    public Stepremotesteps getRemotesteps() {
        return remotesteps;
    }

    /**
     * Sets the value of the remotesteps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stepremotesteps }
     *     
     */
    public void setRemotesteps(Stepremotesteps value) {
        this.remotesteps = value;
    }

    /**
     * Gets the value of the gui property.
     * 
     * @return
     *     possible object is
     *     {@link Stepgui }
     *     
     */
    public Stepgui getGUI() {
        return gui;
    }

    /**
     * Sets the value of the gui property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stepgui }
     *     
     */
    public void setGUI(Stepgui value) {
        this.gui = value;
    }
    
    

    public StepMeta getStepMeta() {
		return stepMeta;
	}

	public void setStepMeta(StepMeta stepMeta) {
		this.stepMeta = stepMeta;
	}

	public TRANSFORMTYPE getTransformType() {
		return transformType;
	}

	public void setTransformType(TRANSFORMTYPE transformType) {
		this.transformType = transformType;
	}
}
