//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.05 at 09:06:54 PM EST 
//


package com.conx.bi.kernel.core.domain.etl.trans;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.flowframe.kernel.common.mdm.domain.MultitenantBaseEntity;

@Entity
@Table(name = "bietltransformation")
public class Transformation
    extends MultitenantBaseEntity
{

    @ManyToOne(targetEntity = Transformation.Info.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "INFO_TRANSFORMATION_HJID")    
    protected Transformation.Info info;
    
    protected String notepads;
    
    @ManyToOne(targetEntity = Transformation.Order.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ORDER__TRANSFORMATION_HJID")    
    protected Transformation.Order order;
    
    @OneToMany(targetEntity = Step.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "STEP_TRANSFORMATION_ID")    
    protected List<Step> step;
    
    protected String stepErrorHandling;
    
    protected String slaveStepCopyPartitionDistribution;
    
    protected String slaveTransformation;

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link Transformation.Info }
     *     
     */
    public Transformation.Info getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transformation.Info }
     *     
     */
    public void setInfo(Transformation.Info value) {
        this.info = value;
    }

    /**
     * Gets the value of the notepads property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "NOTEPADS", length = 255)
    public String getNotepads() {
        return notepads;
    }

    /**
     * Sets the value of the notepads property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotepads(String value) {
        this.notepads = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link Transformation.Order }
     *     
     */
    public Transformation.Order getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transformation.Order }
     *     
     */
    public void setOrder(Transformation.Order value) {
        this.order = value;
    }

    /**
     * Gets the value of the step property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the step property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStep().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Step }
     * 
     * 
     */
    public List<Step> getStep() {
        if (step == null) {
            step = new ArrayList<Step>();
        }
        return this.step;
    }

    /**
     * 
     * 
     */
    public void setStep(List<Step> step) {
        this.step = step;
    }

    /**
     * Gets the value of the stepErrorHandling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "STEPERRORHANDLING", length = 255)
    public String getStepErrorHandling() {
        return stepErrorHandling;
    }

    /**
     * Sets the value of the stepErrorHandling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStepErrorHandling(String value) {
        this.stepErrorHandling = value;
    }

    /**
     * Gets the value of the slaveStepCopyPartitionDistribution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "SLAVESTEPCOPYPARTITIONDISTRI_0", length = 255)
    public String getSlaveStepCopyPartitionDistribution() {
        return slaveStepCopyPartitionDistribution;
    }

    /**
     * Sets the value of the slaveStepCopyPartitionDistribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlaveStepCopyPartitionDistribution(String value) {
        this.slaveStepCopyPartitionDistribution = value;
    }

    /**
     * Gets the value of the slaveTransformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "SLAVETRANSFORMATION", length = 255)
    public String getSlaveTransformation() {
        return slaveTransformation;
    }

    /**
     * Sets the value of the slaveTransformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlaveTransformation(String value) {
        this.slaveTransformation = value;
    }



    @Entity
    @Table(name = "bietltransformation_info")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class Info
    {
        protected String name;
        protected String description;
        protected String extendedDescription;
        protected String transVersion;
        protected String directory;
        protected Transformation.Info.Log log;
        protected Transformation.Info.Maxdate maxdate;
        protected int sizeRowset;
        protected short sleepTimeEmpty;
        protected short sleepTimeFull;
        protected String uniqueConnections;
        protected String feedbackShown;
        protected int feedbackSize;
        protected String usingThreadPriorities;
        protected String sharedObjectsFile;
        protected String captureStepPerformance;
        protected int stepPerformanceCapturingDelay;
        protected String dependencies;
        protected String partitionschemas;
        protected String slaveservers;
        protected String clusterschemas;
        protected String modifiedUser;
        protected String modifiedDate;
        protected Long hjid;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "NAME_", length = 255)
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "DESCRIPTION", length = 255)
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the extendedDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "EXTENDEDDESCRIPTION", length = 255)
        public String getExtendedDescription() {
            return extendedDescription;
        }

        /**
         * Sets the value of the extendedDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtendedDescription(String value) {
            this.extendedDescription = value;
        }

        /**
         * Gets the value of the transVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "TRANSVERSION", length = 255)
        public String getTransVersion() {
            return transVersion;
        }

        /**
         * Sets the value of the transVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransVersion(String value) {
            this.transVersion = value;
        }

        /**
         * Gets the value of the directory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "DIRECTORY", length = 255)
        public String getDirectory() {
            return directory;
        }

        /**
         * Sets the value of the directory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDirectory(String value) {
            this.directory = value;
        }

        /**
         * Gets the value of the log property.
         * 
         * @return
         *     possible object is
         *     {@link Transformation.Info.Log }
         *     
         */
        @ManyToOne(targetEntity = com.conx.bi.kernel.core.domain.etl.trans.Transformation.Info.Log.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "LOG_INFO_HJID")
        public Transformation.Info.Log getLog() {
            return log;
        }

        /**
         * Sets the value of the log property.
         * 
         * @param value
         *     allowed object is
         *     {@link Transformation.Info.Log }
         *     
         */
        public void setLog(Transformation.Info.Log value) {
            this.log = value;
        }

        /**
         * Gets the value of the maxdate property.
         * 
         * @return
         *     possible object is
         *     {@link Transformation.Info.Maxdate }
         *     
         */
        @ManyToOne(targetEntity = com.conx.bi.kernel.core.domain.etl.trans.Transformation.Info.Maxdate.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "MAXDATE_INFO_HJID")
        public Transformation.Info.Maxdate getMaxdate() {
            return maxdate;
        }

        /**
         * Sets the value of the maxdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Transformation.Info.Maxdate }
         *     
         */
        public void setMaxdate(Transformation.Info.Maxdate value) {
            this.maxdate = value;
        }

        /**
         * Gets the value of the sizeRowset property.
         * 
         */
        @Basic
        @Column(name = "SIZEROWSET", precision = 5, scale = 0)
        public int getSizeRowset() {
            return sizeRowset;
        }

        /**
         * Sets the value of the sizeRowset property.
         * 
         */
        public void setSizeRowset(int value) {
            this.sizeRowset = value;
        }

        /**
         * Gets the value of the sleepTimeEmpty property.
         * 
         */
        @Basic
        @Column(name = "SLEEPTIMEEMPTY", precision = 3, scale = 0)
        public short getSleepTimeEmpty() {
            return sleepTimeEmpty;
        }

        /**
         * Sets the value of the sleepTimeEmpty property.
         * 
         */
        public void setSleepTimeEmpty(short value) {
            this.sleepTimeEmpty = value;
        }

        /**
         * Gets the value of the sleepTimeFull property.
         * 
         */
        @Basic
        @Column(name = "SLEEPTIMEFULL", precision = 3, scale = 0)
        public short getSleepTimeFull() {
            return sleepTimeFull;
        }

        /**
         * Sets the value of the sleepTimeFull property.
         * 
         */
        public void setSleepTimeFull(short value) {
            this.sleepTimeFull = value;
        }

        /**
         * Gets the value of the uniqueConnections property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "UNIQUECONNECTIONS", length = 255)
        public String getUniqueConnections() {
            return uniqueConnections;
        }

        /**
         * Sets the value of the uniqueConnections property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUniqueConnections(String value) {
            this.uniqueConnections = value;
        }

        /**
         * Gets the value of the feedbackShown property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "FEEDBACKSHOWN", length = 255)
        public String getFeedbackShown() {
            return feedbackShown;
        }

        /**
         * Sets the value of the feedbackShown property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFeedbackShown(String value) {
            this.feedbackShown = value;
        }

        /**
         * Gets the value of the feedbackSize property.
         * 
         */
        @Basic
        @Column(name = "FEEDBACKSIZE", precision = 5, scale = 0)
        public int getFeedbackSize() {
            return feedbackSize;
        }

        /**
         * Sets the value of the feedbackSize property.
         * 
         */
        public void setFeedbackSize(int value) {
            this.feedbackSize = value;
        }

        /**
         * Gets the value of the usingThreadPriorities property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "USINGTHREADPRIORITIES", length = 255)
        public String getUsingThreadPriorities() {
            return usingThreadPriorities;
        }

        /**
         * Sets the value of the usingThreadPriorities property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUsingThreadPriorities(String value) {
            this.usingThreadPriorities = value;
        }

        /**
         * Gets the value of the sharedObjectsFile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "SHAREDOBJECTSFILE", length = 255)
        public String getSharedObjectsFile() {
            return sharedObjectsFile;
        }

        /**
         * Sets the value of the sharedObjectsFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSharedObjectsFile(String value) {
            this.sharedObjectsFile = value;
        }

        /**
         * Gets the value of the captureStepPerformance property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "CAPTURESTEPPERFORMANCE", length = 255)
        public String getCaptureStepPerformance() {
            return captureStepPerformance;
        }

        /**
         * Sets the value of the captureStepPerformance property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCaptureStepPerformance(String value) {
            this.captureStepPerformance = value;
        }

        /**
         * Gets the value of the stepPerformanceCapturingDelay property.
         * 
         */
        @Basic
        @Column(name = "STEPPERFORMANCECAPTURINGDELAY", precision = 5, scale = 0)
        public int getStepPerformanceCapturingDelay() {
            return stepPerformanceCapturingDelay;
        }

        /**
         * Sets the value of the stepPerformanceCapturingDelay property.
         * 
         */
        public void setStepPerformanceCapturingDelay(int value) {
            this.stepPerformanceCapturingDelay = value;
        }

        /**
         * Gets the value of the dependencies property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "DEPENDENCIES", length = 255)
        public String getDependencies() {
            return dependencies;
        }

        /**
         * Sets the value of the dependencies property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDependencies(String value) {
            this.dependencies = value;
        }

        /**
         * Gets the value of the partitionschemas property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "PARTITIONSCHEMAS", length = 255)
        public String getPartitionschemas() {
            return partitionschemas;
        }

        /**
         * Sets the value of the partitionschemas property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPartitionschemas(String value) {
            this.partitionschemas = value;
        }

        /**
         * Gets the value of the slaveservers property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "SLAVESERVERS", length = 255)
        public String getSlaveservers() {
            return slaveservers;
        }

        /**
         * Sets the value of the slaveservers property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSlaveservers(String value) {
            this.slaveservers = value;
        }

        /**
         * Gets the value of the clusterschemas property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "CLUSTERSCHEMAS", length = 255)
        public String getClusterschemas() {
            return clusterschemas;
        }

        /**
         * Sets the value of the clusterschemas property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClusterschemas(String value) {
            this.clusterschemas = value;
        }

        /**
         * Gets the value of the modifiedUser property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "MODIFIEDUSER", length = 255)
        public String getModifiedUser() {
            return modifiedUser;
        }

        /**
         * Sets the value of the modifiedUser property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModifiedUser(String value) {
            this.modifiedUser = value;
        }

        /**
         * Gets the value of the modifiedDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "MODIFIEDDATE", length = 255)
        public String getModifiedDate() {
            return modifiedDate;
        }

        /**
         * Sets the value of the modifiedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModifiedDate(String value) {
            this.modifiedDate = value;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

        @Entity
        @Table(name = "bietltransformation_info_log")
        @Inheritance(strategy = InheritanceType.JOINED)
        public static class Log
        {
            protected String read;
            protected String write;
            protected String input;
            protected String output;
            protected String update;
            protected String rejected;
            protected String connection;
            protected String table;
            protected String stepPerformanceTable;
            protected String useBatchid;
            protected String useLogfield;
            protected Long hjid;

            /**
             * Gets the value of the read property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "READ_", length = 255)
            public String getRead() {
                return read;
            }

            /**
             * Sets the value of the read property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRead(String value) {
                this.read = value;
            }

            /**
             * Gets the value of the write property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "WRITE_", length = 255)
            public String getWrite() {
                return write;
            }

            /**
             * Sets the value of the write property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWrite(String value) {
                this.write = value;
            }

            /**
             * Gets the value of the input property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "INPUT_", length = 255)
            public String getInput() {
                return input;
            }

            /**
             * Sets the value of the input property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInput(String value) {
                this.input = value;
            }

            /**
             * Gets the value of the output property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "OUTPUT_", length = 255)
            public String getOutput() {
                return output;
            }

            /**
             * Sets the value of the output property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOutput(String value) {
                this.output = value;
            }

            /**
             * Gets the value of the update property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "UPDATE_", length = 255)
            public String getUpdate() {
                return update;
            }

            /**
             * Sets the value of the update property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUpdate(String value) {
                this.update = value;
            }

            /**
             * Gets the value of the rejected property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "REJECTED", length = 255)
            public String getRejected() {
                return rejected;
            }

            /**
             * Sets the value of the rejected property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRejected(String value) {
                this.rejected = value;
            }

            /**
             * Gets the value of the connection property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "CONNECTION_", length = 255)
            public String getConnection() {
                return connection;
            }

            /**
             * Sets the value of the connection property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setConnection(String value) {
                this.connection = value;
            }

            /**
             * Gets the value of the table property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "TABLE_", length = 255)
            public String getTable() {
                return table;
            }

            /**
             * Sets the value of the table property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTable(String value) {
                this.table = value;
            }

            /**
             * Gets the value of the stepPerformanceTable property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "STEPPERFORMANCETABLE", length = 255)
            public String getStepPerformanceTable() {
                return stepPerformanceTable;
            }

            /**
             * Sets the value of the stepPerformanceTable property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStepPerformanceTable(String value) {
                this.stepPerformanceTable = value;
            }

            /**
             * Gets the value of the useBatchid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "USEBATCHID", length = 255)
            public String getUseBatchid() {
                return useBatchid;
            }

            /**
             * Sets the value of the useBatchid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUseBatchid(String value) {
                this.useBatchid = value;
            }

            /**
             * Gets the value of the useLogfield property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "USELOGFIELD", length = 255)
            public String getUseLogfield() {
                return useLogfield;
            }

            /**
             * Sets the value of the useLogfield property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUseLogfield(String value) {
                this.useLogfield = value;
            }

            /**
             * Gets the value of the hjid property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            @Id
            @Column(name = "HJID")
            @GeneratedValue(strategy = GenerationType.AUTO)
            public Long getHjid() {
                return hjid;
            }

            /**
             * Sets the value of the hjid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setHjid(Long value) {
                this.hjid = value;
            }
        }

        @Entity
        @Table(name = "bietltransformation_maxdate")
        @Inheritance(strategy = InheritanceType.JOINED)
        public static class Maxdate
        {
            protected String connection;
            protected String table;
            protected String field;
            protected BigDecimal offset;
            protected BigDecimal maxdiff;
            protected Long hjid;

            /**
             * Gets the value of the connection property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "CONNECTION_", length = 255)
            public String getConnection() {
                return connection;
            }

            /**
             * Sets the value of the connection property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setConnection(String value) {
                this.connection = value;
            }

            /**
             * Gets the value of the table property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "TABLE_", length = 255)
            public String getTable() {
                return table;
            }

            /**
             * Sets the value of the table property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTable(String value) {
                this.table = value;
            }

            /**
             * Gets the value of the field property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "FIELD", length = 255)
            public String getField() {
                return field;
            }

            /**
             * Sets the value of the field property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setField(String value) {
                this.field = value;
            }

            /**
             * Gets the value of the offset property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            @Basic
            @Column(name = "OFFSET_", precision = 20, scale = 10)
            public BigDecimal getOffset() {
                return offset;
            }

            /**
             * Sets the value of the offset property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setOffset(BigDecimal value) {
                this.offset = value;
            }

            /**
             * Gets the value of the maxdiff property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            @Basic
            @Column(name = "MAXDIFF", precision = 20, scale = 10)
            public BigDecimal getMaxdiff() {
                return maxdiff;
            }

            /**
             * Sets the value of the maxdiff property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMaxdiff(BigDecimal value) {
                this.maxdiff = value;
            }

            /**
             * Gets the value of the hjid property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            @Id
            @Column(name = "HJID")
            @GeneratedValue(strategy = GenerationType.AUTO)
            public Long getHjid() {
                return hjid;
            }

            /**
             * Sets the value of the hjid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setHjid(Long value) {
                this.hjid = value;
            }
        }

    }

    @Entity
    @Table(name = "bietltransformation_order")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class Order
    {
        protected Transformation.Order.Hop hop;
        protected Long hjid;

        /**
         * Gets the value of the hop property.
         * 
         * @return
         *     possible object is
         *     {@link Transformation.Order.Hop }
         *     
         */
        @ManyToOne(targetEntity = com.conx.bi.kernel.core.domain.etl.trans.Transformation.Order.Hop.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "HOP_ORDER__HJID")
        public Transformation.Order.Hop getHop() {
            return hop;
        }

        /**
         * Sets the value of the hop property.
         * 
         * @param value
         *     allowed object is
         *     {@link Transformation.Order.Hop }
         *     
         */
        public void setHop(Transformation.Order.Hop value) {
            this.hop = value;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

        @Entity
        @Table(name = "bietltransformation_order_hop")
        @Inheritance(strategy = InheritanceType.JOINED)
        public static class Hop
        {

            protected String from;
            protected String to;
            protected String enabled;
            protected Long hjid;

            /**
             * Gets the value of the from property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "FROM_", length = 255)
            public String getFrom() {
                return from;
            }

            /**
             * Sets the value of the from property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFrom(String value) {
                this.from = value;
            }

            /**
             * Gets the value of the to property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "TO_", length = 255)
            public String getTo() {
                return to;
            }

            /**
             * Sets the value of the to property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTo(String value) {
                this.to = value;
            }

            /**
             * Gets the value of the enabled property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Basic
            @Column(name = "ENABLED", length = 255)
            public String getEnabled() {
                return enabled;
            }

            /**
             * Sets the value of the enabled property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEnabled(String value) {
                this.enabled = value;
            }

            /**
             * Gets the value of the hjid property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            @Id
            @Column(name = "HJID")
            @GeneratedValue(strategy = GenerationType.AUTO)
            public Long getHjid() {
                return hjid;
            }

            /**
             * Sets the value of the hjid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setHjid(Long value) {
                this.hjid = value;
            }
        }
    }

}
