//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.08 at 06:43:54 PM EST 
//


package com.conx.bi.kernel.core.domain.reporting;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.flowframe.kernel.common.mdm.domain.MultitenantBaseEntity;

import com.conx.bi.kernel.core.domain.job.Endpoint;

@Entity
@Table(name = "birptreportingjob")
public class ReportJob
    extends MultitenantBaseEntity
{

    @ManyToOne(targetEntity = ReportTemplate.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TEMPLATE__REPORTJOB_ID")    
    protected ReportTemplate template;
    
    @ManyToOne(targetEntity = Endpoint.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "CONNECTION__REPORTJOB_ID")    
    protected Endpoint connection;

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link ReportTemplate }
     *     
     */
    public ReportTemplate getTemplate() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportTemplate }
     *     
     */
    public void setTemplate(ReportTemplate value) {
        this.template = value;
    }

    /**
     * Gets the value of the connection property.
     * 
     * @return
     *     possible object is
     *     {@link Endpoint }
     *     
     */
    public Endpoint getConnection() {
        return connection;
    }

    /**
     * Sets the value of the connection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Endpoint }
     *     
     */
    public void setConnection(Endpoint value) {
        this.connection = value;
    }
}
