package org.flowframe.erp.integration.adaptors.stripe.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-05-08T13:24:53.477-04:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "IEventBusinessService", 
                  wsdlLocation = "http://stage.conxbi.com:8182/cxf/org/flowframe/erp/integration/adaptors/stripe/services/IEventBusinessService?wsdl",
                  targetNamespace = "http://services.stripe.adaptors.integration.erp.flowframe.org/") 
public class IEventBusinessService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.stripe.adaptors.integration.erp.flowframe.org/", "IEventBusinessService");
    public final static QName IEventBusinessServicePort = new QName("http://services.stripe.adaptors.integration.erp.flowframe.org/", "IEventBusinessServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://stage.conxbi.com:8182/cxf/org/flowframe/erp/integration/adaptors/stripe/services/IEventBusinessService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IEventBusinessService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://stage.conxbi.com:8182/cxf/org/flowframe/erp/integration/adaptors/stripe/services/IEventBusinessService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IEventBusinessService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IEventBusinessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IEventBusinessService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IEventBusinessServicePortType
     */
    @WebEndpoint(name = "IEventBusinessServicePort")
    public IEventBusinessServicePortType getIEventBusinessServicePort() {
        return super.getPort(IEventBusinessServicePort, IEventBusinessServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEventBusinessServicePortType
     */
    @WebEndpoint(name = "IEventBusinessServicePort")
    public IEventBusinessServicePortType getIEventBusinessServicePort(WebServiceFeature... features) {
        return super.getPort(IEventBusinessServicePort, IEventBusinessServicePortType.class, features);
    }

}
