//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.07 at 10:18:48 AM EST 
//


package com.conx.bi.kernel.core.domain.job;


public enum ComponentType {

    FTP,
    JDBC,
    FILE, 
    SFTP, 
    FTPS, 
    SpringWS;

    public String value() {
        return name();
    }

    public static ComponentType fromValue(String v) {
        return valueOf(v);
    }

}
