//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.07 at 10:18:48 AM EST 
//


package com.conx.bi.kernel.core.domain.job;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.flowframe.kernel.common.mdm.domain.MultitenantBaseEntity;

import com.conx.bi.kernel.core.domain.etl.trans.Step;


@Entity
@Table(name = "bijobendpointmetastep")
public class EndpointMetaStep
    extends MultitenantBaseEntity
{

    protected Endpoint endpoint;
    protected Step metaStep;

    /**
     * Gets the value of the endpoint property.
     * 
     * @return
     *     possible object is
     *     {@link Endpoint }
     *     
     */
    @ManyToOne(targetEntity = Endpoint.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ENDPOINT_ENDPOINTMETASTEP_ID")
    public Endpoint getEndpoint() {
        return endpoint;
    }

    /**
     * Sets the value of the endpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Endpoint }
     *     
     */
    public void setEndpoint(Endpoint value) {
        this.endpoint = value;
    }

    /**
     * Gets the value of the metaStep property.
     * 
     * @return
     *     possible object is
     *     {@link Step }
     *     
     */
    @ManyToOne(targetEntity = Step.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "METASTEP_ENDPOINTMETASTEP_ID")
    public Step getMetaStep() {
        return metaStep;
    }

    /**
     * Sets the value of the metaStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Step }
     *     
     */
    public void setMetaStep(Step value) {
        this.metaStep = value;
    }
}
