//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.07 at 10:18:48 AM EST 
//


package com.conx.bi.kernel.core.domain.job;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.flowframe.kernel.common.mdm.domain.MultitenantBaseEntity;



@Entity
@Table(name = "bijobendpointmetajobinputmappingstep")
public class EndpointMetaJobInputMappingStep
    extends MultitenantBaseEntity
{

    protected EndpointMetaStep endpointMetaStep;
    protected Job job;

    /**
     * Gets the value of the endpointMetaStep property.
     * 
     * @return
     *     possible object is
     *     {@link EndpointMetaStep }
     *     
     */
    @ManyToOne(targetEntity = EndpointMetaStep.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ENDPOINTMETASTEP_ENDPOINTMET_0")
    public EndpointMetaStep getEndpointMetaStep() {
        return endpointMetaStep;
    }

    /**
     * Sets the value of the endpointMetaStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndpointMetaStep }
     *     
     */
    public void setEndpointMetaStep(EndpointMetaStep value) {
        this.endpointMetaStep = value;
    }

    /**
     * Gets the value of the job property.
     * 
     * @return
     *     possible object is
     *     {@link Job }
     *     
     */
    @ManyToOne(targetEntity = Job.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "JOB_ENDPOINTMETAJOBINPUTMAPP_0")
    public Job getJob() {
        return job;
    }

    /**
     * Sets the value of the job property.
     * 
     * @param value
     *     allowed object is
     *     {@link Job }
     *     
     */
    public void setJob(Job value) {
        this.job = value;
    }
}
