//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.07 at 10:18:48 AM EST 
//

package com.conx.bi.kernel.core.domain.job;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.flowframe.kernel.common.mdm.domain.MultitenantBaseEntity;
import org.flowframe.kernel.common.mdm.domain.preferences.Preferences;

@Entity
@Table(name = "bijobendpoint")
public class Endpoint extends MultitenantBaseEntity  {

	protected boolean istemplate;
	protected String epId;

	@ManyToOne(targetEntity = Endpoint.class, cascade = { CascadeType.ALL })
	@JoinColumn(name = "TEMPLATEENDPOINT_ENDPOINT_ID")
	protected Endpoint templateEndpoint;

	protected ComponentType componentType;

	@ManyToOne(targetEntity = Preferences.class, cascade = { CascadeType.ALL }, fetch = FetchType.EAGER)
	@JoinColumn(name = "PROPERTIES_ENDPOINT_ID")
	protected Preferences properties;

	/**
	 * Gets the value of the istemplate property.
	 * 
	 */
	@Basic
	@Column(name = "ISTEMPLATE")
	public boolean isIstemplate() {
		return istemplate;
	}

	/**
	 * Sets the value of the istemplate property.
	 * 
	 */
	public void setIstemplate(boolean value) {
		this.istemplate = value;
	}

	/**
	 * Gets the value of the epId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Basic
	@Column(name = "EPID", length = 255)
	public String getEpId() {
		return epId;
	}

	/**
	 * Sets the value of the epId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEpId(String value) {
		this.epId = value;
	}

	/**
	 * Gets the value of the templateEndpoint property.
	 * 
	 * @return possible object is {@link Endpoint }
	 * 
	 */
	public Endpoint getTemplateEndpoint() {
		return templateEndpoint;
	}

	/**
	 * Sets the value of the templateEndpoint property.
	 * 
	 * @param value
	 *            allowed object is {@link Endpoint }
	 * 
	 */
	public void setTemplateEndpoint(Endpoint value) {
		this.templateEndpoint = value;
	}

	/**
	 * Gets the value of the componentType property.
	 * 
	 * @return possible object is {@link TRANSFORMTYPE }
	 * 
	 */
	@Basic
	@Column(name = "COMPONENTTYPE", length = 255)
	@Enumerated(EnumType.STRING)
	public ComponentType getComponentType() {
		return componentType;
	}

	/**
	 * Sets the value of the componentType property.
	 * 
	 * @param value
	 *            allowed object is {@link TRANSFORMTYPE }
	 * 
	 */
	public void setComponentType(ComponentType value) {
		this.componentType = value;
	}

	/**
	 * Gets the value of the properties property.
	 * 
	 * @return possible object is {@link Preferences }
	 * 
	 */
	public Preferences getProperties() {
		return properties;
	}

	/**
	 * Sets the value of the properties property.
	 * 
	 * @param value
	 *            allowed object is {@link Preferences }
	 * 
	 */
	public void setProperties(Preferences value) {
		this.properties = value;
	}
}
