//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.07 at 10:18:48 AM EST 
//


package com.conx.bi.kernel.core.domain.job;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


public enum JDBCServerType {

    MY_SQL("MySQL"),
    MSSQLSERVER_2005("MSSQLSERVER2005"),
    ORACLE("ORACLE");
    private final String value;

    JDBCServerType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static JDBCServerType fromValue(String v) {
        for (JDBCServerType c: JDBCServerType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
