//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.07 at 10:18:48 AM EST 
//


package com.conx.bi.kernel.core.domain.job;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Table;

import org.flowframe.kernel.common.mdm.domain.MultitenantBaseEntity;



@Entity
@Table(name = "bijobjdbcdrivertype")
public class JDBCDriverType
    extends MultitenantBaseEntity
{
    protected JDBCServerType serverType;
    protected String driverClass;
    protected String urlPrompt;

    /**
     * Gets the value of the serverType property.
     * 
     * @return
     *     possible object is
     *     {@link JDBCServerType }
     *     
     */
    @Basic
    @Column(name = "SERVERTYPE", length = 255)
    @Enumerated(EnumType.STRING)
    public JDBCServerType getServerType() {
        return serverType;
    }

    /**
     * Sets the value of the serverType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JDBCServerType }
     *     
     */
    public void setServerType(JDBCServerType value) {
        this.serverType = value;
    }

    /**
     * Gets the value of the driverClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "DRIVERCLASS", length = 255)
    public String getDriverClass() {
        return driverClass;
    }

    /**
     * Sets the value of the driverClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverClass(String value) {
        this.driverClass = value;
    }

    /**
     * Gets the value of the urlPrompt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "URLPROMPT", length = 255)
    public String getUrlPrompt() {
        return urlPrompt;
    }

    /**
     * Sets the value of the urlPrompt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlPrompt(String value) {
        this.urlPrompt = value;
    }

}
