//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.07 at 10:18:48 AM EST 
//


package com.conx.bi.kernel.core.domain.job;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.flowframe.kernel.common.mdm.domain.MultitenantBaseEntity;



@Entity
@Table(name = "bijobjob")
public class Job
    extends MultitenantBaseEntity
{

    protected JobMeta jobMetaTemplate;

    /**
     * Gets the value of the jobMetaTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link JobMeta }
     *     
     */
    @ManyToOne(targetEntity = JobMeta.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "JOBMETATEMPLATE_JOB_ID")
    public JobMeta getJobMetaTemplate() {
        return jobMetaTemplate;
    }

    /**
     * Sets the value of the jobMetaTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobMeta }
     *     
     */
    public void setJobMetaTemplate(JobMeta value) {
        this.jobMetaTemplate = value;
    }
}
