//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.07 at 10:18:48 AM EST 
//


package com.conx.bi.kernel.core.domain.job;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.flowframe.kernel.common.mdm.domain.MultitenantBaseEntity;


@Entity
@Table(name = "bijobjobmeta")
public class JobMeta
    extends MultitenantBaseEntity
{

    protected long camelRouteId;

    /**
     * Gets the value of the camelRouteId property.
     * 
     */
    @Basic
    @Column(name = "CAMELROUTEID", precision = 20, scale = 0)
    public long getCamelRouteId() {
        return camelRouteId;
    }

    /**
     * Sets the value of the camelRouteId property.
     * 
     */
    public void setCamelRouteId(long value) {
        this.camelRouteId = value;
    }
}
