//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.07 at 10:18:48 AM EST 
//


package com.conx.bi.kernel.core.domain.job;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

@Entity(name = "OneInputOneOutputEtlJob")
public class OneInputOneOutputEtlJob
    extends Job
{

    protected EndpointMetaStep inputEndpointMetaStep;
    protected EndpointMetaJobInputMappingStep inputEndpointMetaStepMapper;

    /**
     * Gets the value of the inputEndpointMetaStep property.
     * 
     * @return
     *     possible object is
     *     {@link EndpointMetaStep }
     *     
     */
    @ManyToOne(targetEntity = EndpointMetaStep.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "INPUTENDPOINTMETASTEP_ONEINP_0")
    public EndpointMetaStep getInputEndpointMetaStep() {
        return inputEndpointMetaStep;
    }

    /**
     * Sets the value of the inputEndpointMetaStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndpointMetaStep }
     *     
     */
    public void setInputEndpointMetaStep(EndpointMetaStep value) {
        this.inputEndpointMetaStep = value;
    }

    /**
     * Gets the value of the inputEndpointMetaStepMapper property.
     * 
     * @return
     *     possible object is
     *     {@link EndpointMetaJobInputMappingStep }
     *     
     */
    @ManyToOne(targetEntity = EndpointMetaJobInputMappingStep.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "INPUTENDPOINTMETASTEPMAPPER__0")
    public EndpointMetaJobInputMappingStep getInputEndpointMetaStepMapper() {
        return inputEndpointMetaStepMapper;
    }

    /**
     * Sets the value of the inputEndpointMetaStepMapper property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndpointMetaJobInputMappingStep }
     *     
     */
    public void setInputEndpointMetaStepMapper(EndpointMetaJobInputMappingStep value) {
        this.inputEndpointMetaStepMapper = value;
    }
}
